# Use Python base image
FROM python:3.9

# Set working directory in the container
WORKDIR /media/sf_data_engineering/group_project/data_engineering_petrol_pump

# Copy requirements file
COPY requirements.txt ./

# Install dependencies
RUN apt-get update && apt-get install -y \
    libspatialindex-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt

# Copy the Python script into the container
COPY etl_pump_locations.py ./

# Run the Python script when the container starts
CMD ["python", "./etl_pump_locations.py"]
