merge
into
	prod_petrol_pump_locations.pump_locations as tgt
		using stg_petrol_pump_locations.pump_locations as src
on tgt.osmid = src.osmid
	when matched
then
update
set
	element_type = src.element_type,
	--osmid = src.osmid,
	amenity = src.amenity,
	brand = src.brand,
	"brand:wikidata" = src."brand:wikidata",
	"brand:wikipedia" = src."brand:wikipedia",
	"name" = src."name",
	"addr:city" = src."addr:city",
	"addr:country" = src."addr:country",
	"addr:housenumber" = src."addr:housenumber",
	"addr:postcode" = src."addr:postcode",
	"addr:street" = src."addr:street",
	branch = src.branch,
	opening_hours = src.opening_hours,
	"addr:suburb" = src."addr:suburb",
	"operator" = src."operator",
	"ref:linz:address_id" = src."ref:linz:address_id",
	note = src.note,
	compressed_air = src.compressed_air,
	"fuel:diesel" = src."fuel:diesel",
	"fuel:octane_91" = src."fuel:octane_91",
	"fuel:octane_95" = src."fuel:octane_95",
	phone = src.phone,
	website = src.website,
	"source" = src."source",
	wheelchair = src.wheelchair,
	"fuel:electricity" = src."fuel:electricity",
	"fuel:lpg" = src."fuel:lpg",
	"fuel:octane_98" = src."fuel:octane_98",
	self_service = src.self_service,
	official_name = src.official_name,
	"fuel:HGV_diesel" = src."fuel:HGV_diesel",
	"payment:cash" = src."payment:cash",
	"payment:girocard" = src."payment:girocard",
	"payment:mastercard" = src."payment:mastercard",
	"payment:visa" = src."payment:visa",
	shop = src.shop,
	"name:mi" = src."name:mi",
	landuse = src.landuse,
	layer = src.layer,
	"payment:credit_cards" = src."payment:credit_cards",
	building = src.building,
	height = src.height,
	diesel = src.diesel,
	"fuel:GTL_diesel" = src."fuel:GTL_diesel",
	"fuel:cng" = src."fuel:cng",
	"fuel:e10" = src."fuel:e10",
	"fuel:e85" = src."fuel:e85",
	"source:geometry" = src."source:geometry",
	"building:levels" = src."building:levels",
	"roof:shape" = src."roof:shape",
	toilets = src.toilets,
	atm = src.atm,
	cafe = src.cafe,
	car_wash = src.car_wash,
	check_date = src.check_date,
	"payment:american_express" = src."payment:american_express",
	"payment:visa_debit" = src."payment:visa_debit",
	service = src.service,
	"contact:phone" = src."contact:phone",
	"fuel:adblue" = src."fuel:adblue",
	"fuel:octane_100" = src."fuel:octane_100",
	"payment:debit_cards" = src."payment:debit_cards",
	smoking = src.smoking,
	"operator:wikidata" = src."operator:wikidata",
	start_date = src.start_date,
	ways = src.ways,
	"type" = src."type",
	update_time = src."insert_time",
	nodes = src.nodes,
	geometry = src.geometry
	when not matched
then
insert
	(element_type,
	osmid,
	amenity,
	brand,
	"brand:wikidata",
	"brand:wikipedia",
	"name",
	"addr:city",
	"addr:country",
	"addr:housenumber",
	"addr:postcode",
	"addr:street",
	branch,
	opening_hours,
	"addr:suburb",
	"operator",
	"ref:linz:address_id",
	note,
	compressed_air,
	"fuel:diesel",
	"fuel:octane_91",
	"fuel:octane_95",
	phone,
	website,
	"source",
	wheelchair,
	"fuel:electricity",
	"fuel:lpg",
	"fuel:octane_98",
	self_service,
	official_name,
	"fuel:HGV_diesel",
	"payment:cash",
	"payment:girocard",
	"payment:mastercard",
	"payment:visa",
	shop,
	"name:mi",
	landuse,
	layer,
	"payment:credit_cards",
	building,
	height,
	diesel,
	"fuel:GTL_diesel",
	"fuel:cng",
	"fuel:e10",
	"fuel:e85",
	"source:geometry",
	"building:levels",
	"roof:shape",
	toilets,
	atm,
	cafe,
	car_wash,
	check_date,
	"payment:american_express",
	"payment:visa_debit",
	service,
	"contact:phone",
	"fuel:adblue",
	"fuel:octane_100",
	"payment:debit_cards",
	smoking,
	"operator:wikidata",
	start_date,
	ways,
	"type",
	INSERT_time,
	nodes,
	geometry
	)
values (src.element_type,
src.osmid,
src.amenity,
src.brand,
src."brand:wikidata",
src."brand:wikipedia",
src."name",
src."addr:city",
src."addr:country",
src."addr:housenumber",
src."addr:postcode",
src."addr:street",
src.branch,
src.opening_hours,
src."addr:suburb",
src."operator",
src."ref:linz:address_id",
src.note,
src.compressed_air,
src."fuel:diesel",
src."fuel:octane_91",
src."fuel:octane_95",
src.phone,
src.website,
src."source",
src.wheelchair,
src."fuel:electricity",
src."fuel:lpg",
src."fuel:octane_98",
src.self_service,
src.official_name,
src."fuel:HGV_diesel",
src."payment:cash",
src."payment:girocard",
src."payment:mastercard",
src."payment:visa",
src.shop,
src."name:mi",
src.landuse,
src.layer,
src."payment:credit_cards",
src.building,
src.height,
src.diesel,
src."fuel:GTL_diesel",
src."fuel:cng",
src."fuel:e10",
src."fuel:e85",
src."source:geometry",
src."building:levels",
src."roof:shape",
src.toilets,
src.atm,
src.cafe,
src.car_wash,
src.check_date,
src."payment:american_express",
src."payment:visa_debit",
src.service,
src."contact:phone",
src."fuel:adblue",
src."fuel:octane_100",
src."payment:debit_cards",
src.smoking,
src."operator:wikidata",
src.start_date,
src.ways,
src."type",
SRC.insert_time,
SRC.nodes,
SRC.geometry
);
 
